spring.application.name=learningSpringBootApp

spring.datasource.url=jdbc:mysql://localhost:3306/newsapp
spring.datasource.username=root
spring.datasource.password=ansh@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true